llm-service:
  device: gpu
  models:
    llama-3-2-3b-instruct:
      enabled: true

clusterGroup:
  namespaces:
    openshift-nfd:
    nvidia-gpu-operator:

  subscriptions:
    nfd:
      name: nfd
      namespace: openshift-nfd
    nvidia:
      name: gpu-operator-certified
      namespace: nvidia-gpu-operator
      source: certified-operators

  applications:
    nfd:
      name: nfd
      namespace: openshift-nfd
      path: charts/nfd
    nvidia-config:
      name: nvidia-config
      namespace: nvidia-gpu-operator
      path: charts/nvidia-config

  imperative:
    jobs:
      - name: deploy-nvidia-gpu
        playbook: ansible/deploy_nvidia_gpu_aws.yaml
        verbosity: -vvv
    clusterRoleYaml:
      - apiGroups:
          - "*"
        resources:
          - machinesets
          - persistentvolumeclaims
          - datavolumes
          - dataimportcrons
          - datasources
        verbs:
          - "*"
      - apiGroups:
          - "*"
        resources:
          - "*"
        verbs:
          - get
          - list
          - watch
