global:
  pattern: ai-quickstart-rag
  # device should be one of:
  #   cpu
  #   gpu (NVIDIA GPU configuration)
  #   hpu (Intel Gaudi)
  #   gpu-amd (AMD GPU configuration)
  device: gpu
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
