global:
  pattern: ai-quickstart-rag
  # device should be cpu, nvidia, intel, or amd
  device: nvidia
main:
  clusterGroupName: prod
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: 0.9.*
