clusterGroup:
  name: prod

  namespaces:
    ai-quickstart-rag:
    vault:
    golang-external-secrets:
    redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    openshift-serverless:
        operatorGroup: true
        targetNamespaces: []
    openshift-pipelines:
    redhat-ods-applications:

  sharedValueFiles:
    - '/overrides/values-{{ $.Values.global.device }}.yaml'

  subscriptions:
    serverless:
      name: serverless-operator
      namespace: openshift-serverless
    servicemesh:
      name: servicemeshoperator
      namespace: openshift-operators
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
    pipelines:
      name: openshift-pipelines-operator-rh

  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.1.*

    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*

    rag-quickstart:
      name: rag-quickstart
      namespace: ai-quickstart-rag
      repoURL: https://github.com/rh-ai-quickstart/RAG
      chartVersion: dev
      path: deploy/helm/rag
      extraValueFiles:
        - $patternref/overrides/rag-quickstart.yaml

    pattern-secrets:
      name: pattern-secrets
      namespace: ai-quickstart-rag
      path: charts/pattern-secrets

    data-science-cluster:
      name: data-science-cluster
      namespace: ai-quickstart-rag
      path: charts/dsc
