apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configure-pipeline
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rag-pipeline-secrets
    template:
      type: Opaque
      engineVersion: v2
      data:
        MINIO_ENDPOINT: {{ printf "http://{{ .host }}.%s.svc.cluster.local:{{ .port }}" .Release.Namespace | quote }}
        MINIO_ACCESS_KEY: {{ printf "{{ .user }}" | quote }}
        MINIO_SECRET_KEY: {{ printf "{{ .password }}" | quote }}
        LLAMASTACK_BASE_URL: {{ printf "http://llamastack.%s.svc.cluster.local:8321" .Release.Namespace | quote }}
        DS_PIPELINE_URL: {{ printf  "https://ds-pipeline-dspa.%s.svc.cluster.local:8888" .Release.Namespace | quote }}
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/hub/minio
      property: user
  - secretKey: password
    remoteRef:
      key: secret/data/hub/minio
      property: password
  - secretKey: host
    remoteRef:
      key: secret/data/hub/minio
      property: host
  - secretKey: port
    remoteRef:
      key: secret/data/hub/minio
      property: port
