apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-service
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: huggingface-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        HF_TOKEN: {{ printf "{{ .hf_token }}" | quote }}
  data:
  - secretKey: hf_token
    remoteRef:
      key: secret/data/hub/llm-service
      property: hf_token
