apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: minio
    template:
      type: Opaque
      engineVersion: v2
      data:
        user: {{ printf "{{ .user }}" | quote }}
        password: {{ printf "{{ .password }}" | quote }}
        host: {{ printf "{{ .host }}" | quote }}
        port: {{ printf "{{ .port }}" | quote }}
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/hub/minio
      property: user
  - secretKey: password
    remoteRef:
      key: secret/data/hub/minio
      property: password
  - secretKey: host
    remoteRef:
      key: secret/data/hub/minio
      property: host
  - secretKey: port
    remoteRef:
      key: secret/data/hub/minio
      property: port
