apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgvector
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgvector
    template:
      type: Opaque
      engineVersion: v2
      data:
        user: {{ printf "{{ .user }}" | quote }}
        password: {{ printf "{{ .password }}" | quote }}
        dbname: {{ printf "{{ .dbname }}" | quote }}
        host: {{ printf "{{ .host }}" | quote }}
        port: {{ printf "{{ .port }}" | quote }}
        jdbc-uri: {{ printf "jdbc:postgresql://{{ .host }}.%s:{{ .port }}/{{ .dbname }}?password={{ .password }}&user={{ .user }}" .Release.Namespace | quote }}
        uri: {{ printf "postgresql://{{ .user }}:{{ .password }}@{{ .host }}.%s:{{ .port }}/{{ .dbname }}" .Release.Namespace | quote }}
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/hub/pgvector
      property: user
  - secretKey: password
    remoteRef:
      key: secret/data/hub/pgvector
      property: password
  - secretKey: dbname
    remoteRef:
      key: secret/data/hub/pgvector
      property: dbname
  - secretKey: host
    remoteRef:
      key: secret/data/hub/pgvector
      property: host
  - secretKey: port
    remoteRef:
      key: secret/data/hub/pgvector
      property: port
